### ISSUE TITLE
DB design

### ISSUE THREAD

**Issue by ghost** [AT-PHPIntership/danang_bus#1]
![photo on 3-16-17 at 4 05 pm](https://cloud.githubusercontent.com/assets/16182754/23988830/8e08d188-0a62-11e7-88e0-39c1e1b76daa.jpg)

**Comment by at-dieulexuan** [comment]
[https://drive.google.com/file/d/0BxyYLt7osxhEWXVGQmtlSlMtT3c/view?usp=sharing](url)
